Version 0.2.0
PilotsTradeNetwork/ModBot pull request #13
Opened 2023-10-14 17:55 UTC by TuggyBoat

bot.py
-renamed bot object class to ModBot

constants.py
-fixed `get_guild()`, function is not async

database.py
-fixed search function to properly search database

-added `insert_infraction()` function

Helpers.py
-created Helpers.py

-added `create_thread`, `find_thread`, `display_infractions`, and `get_rule` functions

ModCommands.py
-added `InfractionReport` modal for future infraction reporting, only sends a message to channel as of now

-moved rule retrieval to Helpers.py

-added `warn` command, only displays infractions right now

-added `find_thread` command, gets an infraction thread by user id

-added `view_infractions` interaction, displays a user's infractions

-added `infraction_message` interaction, for future usage in message deletion and reporting, only calls for `InfractionReport` modal

2023-10-18 08:45 UTC, cimspin requested changes
All great stuff. I can do the error handler bits if you like.

2023-10-18 08:45 UTC, cimspin commented on ptn/modbot/botcommands/ModCommands.py
> +            except ValueError:
This should be moved to the Error Handler. We can create our own ValueError handler or just use CustomError, e.g.
```try:
    error = 'your error text'
    raise CustomError(error)
except Exception as e:
    return await on_generic_error(interaction, e)```
This is to enforce a consistent format for error reporting and logging.

2023-10-18 08:45 UTC, cimspin commented on ptn/modbot/botcommands/ModCommands.py
> +        except ValueError:
➡️ Error Handler :]

2023-10-18 08:45 UTC, cimspin commented on ptn/modbot/botcommands/ModCommands.py
> +    if message.author.bot:
This can also be shipped off to CustomError

2023-10-18 08:45 UTC, cimspin commented on ptn/modbot/database/database.py
> +            f"SELECT * FROM infractions WHERE {searchcolumn} = ?", (searchterm,)
♥

2023-10-18 08:45 UTC, cimspin commented on ptn/modbot/modules/Helpers.py
> +def create_thread(member: discord.Member, guild: discord.Member):
`guild: discord.Guild`

2023-10-18 08:45 UTC, cimspin commented on ptn/modbot/modules/Helpers.py
> +    except Exception as e:
⋆｡  🎀  𝒯💙 𝓉𝒽𝑒 𝑒𝓇𝓇❀𝓇 𝒽𝒶𝓃𝒹𝓁𝑒𝓇 𝓅𝓁𝑒𝒶𝓈𝑒  🎀  ｡⋆

2023-10-21 04:18 UTC, TuggyBoat commented
Did the Error handling work, all use CustomError now until we decide to use other methods

2023-10-21 08:29 UTC, cimspin approved these changes

2023-10-21 18:27 UTC, merged